<main class="container py-5">  
    <h2 class="mb-5">Nos catégories de films</h2>  
    <section class="row">  
        <article class="card col-3 mx-2 p-5">  
            <header>  
                <h3 class="card-title">Nom de la catégorie 1</h3>  
            </header>  
            <p class="card-text">  
                Description de la catégorie 1  
            </p>  
            <footer>  
                <a href="/res03-routeur/categories/action" class="btn btn-primary">Les films de la catégorie 1</a>  
            </footer>  
        </article>  
        <article class="card col-3 mx-2 p-5">  
            <header>  
                <h3 class="card-title">Nom de la catégorie 2</h3>  
            </header>  
            <p class="card-text">  
                Description de la catégorie 2  
            </p>  
            <footer>  
                <a href="//res03-routeurcategories/heroic-fantasy" class="btn btn-primary">Les films de la catégorie 2</a>  
            </footer>  
        </article>  
        <article class="card col-3 mx-2 p-5">  
            <header>  
                <h3 class="card-title">Nom de la catégorie 3</h3>  
            </header>  
            <p class="card-text">  
                Description de la catégorie 3  
            </p>  
            <footer>  
                <a href="/res03-routeur/categories/science-fiction" class="btn btn-primary">Les films de la catégorie 3</a>  
            </footer>  
        </article>  
    </section>  
</main>