<main class="container py-5">  
    <article class="card col-12 p-5">  
        <header>  
            <h2 class="card-title mb-3">  
                Le titre du film  
            </h2>  
            <h3 class="card-subtitle mb-4">  
                Catégorie 1 du film, catégorie 2 du film  
            </h3>  
        </header>  
        <p class="card-text">  
            Description du film  
        </p>  
        <footer>  
            <p class="btn btn-light">  
                Prix du film €  
            </p>  
        </footer>  
    </article>  
</main>