<main class="container py-5">  
    <h2 class="mb-5">La liste des films</h2>  
    <section class="row">  
        <article class="card col-3 mx-2 p-5">  
            <header>  
                <h3 class="card-title">Nom du film 1</h3>  
            </header>  
            <p class="card-text">  
                Description du film 1  
            </p>  
            <footer>  
                <a href="/res03-routeur/produits/the-expendables" class="btn btn-success">Le film 1</a>  
            </footer>  
        </article>  
        <article class="card col-3 mx-2 p-5">  
            <header>  
                <h3 class="card-title">Nom du film 2</h3>  
            </header>  
            <p class="card-text">  
                Description du film 2  
            </p>  
            <footer>  
                <a href="/res03-routeur/produits/the-expendables" class="btn btn-success">Le film 2</a>  
            </footer>  
        </article>  
        <article class="card col-3 mx-2 p-5">  
            <header>  
                <h3 class="card-title">Nom du film 3</h3>  
            </header>  
            <p class="card-text">  
                Description du film 3  
            </p>  
            <footer>  
                <a href="/res03-routeur/produits/the-expendables" class="btn btn-success">Le film 3</a>  
            </footer>  
        </article>  
    </section>  
</main>